-- Create database qrdomestic and schema qrpayment by UI
CREATE DATABASE qrdomestic;
CREATE SCHEMA IF NOT EXISTS qrpayment;

create table if not exists qrpayment.application_parameter
(
id          bigint generated by default as identity
primary key,
  name        varchar(255) not null
  unique,
  value       varchar(255),
  description varchar(255),
  created_at  timestamp,
  updated_at  timestamp
);

create table if not exists qrpayment.transaction_log
(
id                     bigint generated by default as identity
primary key,
  trace_id               varchar(255),
  api_service            varchar(255),
  issuer_rc              varchar(255),
  acquirer_rc            varchar(255),
  issuer_rrn             varchar(255),
  acquirer_rrn           varchar(255),
  switching_rrn          varchar(255),
  amount                 numeric(20, 2),
issuer_body_request    text,
issuer_body_response   text,
acquirer_body_request  text,
acquirer_body_response text,
additional_info        varchar(255),
created_at             timestamp,
updated_at             timestamp
);

create index if not exists transaction_log_issuer_rrn_idx
on qrpayment.transaction_log (issuer_rrn, api_service);

create table if not exists qrpayment.rc_mapping
(
id                bigint generated by default as identity
primary key,
  service_code      varchar(255),
  input_rc          varchar(255),
  output_rc         varchar(255),
  input_rc_message  varchar(255),
  output_rc_message varchar(255),
  created_at        timestamp,
  updated_at        timestamp
);

create index if not exists rc_mapping_service_code_idx
on qrpayment.rc_mapping (service_code);

create table if not exists qrpayment.credential_data
(
id                    bigint generated by default as identity
primary key,
  credential_identifier varchar(1000),
  credential_name       varchar(255),
  username              varchar(255),
  password              varchar(1000),
  api_key               varchar(1000),
  secret_key            varchar(1000),
  credential_target     varchar(200),
  description           varchar(255),
  created_at            timestamp,
  updated_at            timestamp
);

create table if not exists qrpayment.access_token
(
  credential_identifier varchar(1000) not null,
  access_token          varchar(1000) not null,
  token_type            varchar(100),
  token_mode            varchar(100),
  expires_in            bigint,
  created_at            timestamp,
  updated_at            timestamp,
primary key (credential_identifier, access_token)
);
